// Favicon and progressive web app manifest

module.exports = {
    name: 'Webpack Boilerplate',
    // Short human-readable name for the application (<12 chars)
    short_name: 'Boilerplate',
    // General description of what the web application does.
    description: 'Webpack 3 boilerplate for quickly build up application',
    // Background color displayed while the css is loading
    background_color: '#009688',
    theme_color: '#009688',
    start_url: ".",
    // favicon and pwa icon for android (ios icons and start icon are generated by the favicon plugin)
    icons: {
        // File path from root
        src: 'src/assets/images/webpack-logo.png',
        sizes: [36, 48, 72, 96, 144, 512],
    }
};
